{% set name = "dydxprotocol-v4-proto-py" %}
{% set version = "6.0.3" %}

package:
  name: dydxprotocol-v4-proto-split
  version: {{ version }}

source:
  url: https://github.com/dydxprotocol/v4-chain/archive/refs/tags/protocol/v{{ version }}.tar.gz
  sha256: db7be105d5016fb1b3265b301356698f0d4ab10b367d0d06642913a0775d73df
  patches:
    - patches/0001-use-local-protobuf-makefile.patch

build:
  noarch: python
  number: 1

requirements:
  build:
    - make
    - sed
    - buf
    - perl
  host:
    - grpcio-tools >=1.54
    - grpcio >=1.54
    - protobuf >=4.23
    - python >=3.9

outputs:
  - name: dydxprotocol-v4-proto-py
    script: install-py.sh
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.9
        - setuptools
      run:
        - grpcio-tools >=1.54
        - grpcio >=1.54
        - protobuf >=4.23
        - python >=3.9
    test:
      imports:
        - v4_proto
      requires:
        - pip
      commands:
        - pip check
      downstreams:
        - dydx-v4-client

  # - Naming conversion
  - name: dydxprotocol_v4_proto_py
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('dydxprotocol-v4-proto-py', exact=True) }}
    test:
      imports:
        - v4_proto
      requires:
        - pip
      commands:
        - pip check

  # Package name required by v4-client upstream pyproject.toml
  - name: v4-proto
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('dydxprotocol-v4-proto-py', exact=True) }}
    test:
      imports:
        - v4_proto
      requires:
        - pip
      commands:
        - pip check

  # Alias
  - name: v4_proto
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('dydxprotocol-v4-proto-py', exact=True) }}
    test:
      imports:
        - v4_proto
      requires:
        - pip
      commands:
        - pip check

  # Alias
  - name: dydx-v4-proto
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('dydxprotocol-v4-proto-py', exact=True) }}
    test:
      imports:
        - v4_proto
      requires:
        - pip
      commands:
        - pip check

  # Alias
  - name: dydx_v4_proto
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('dydxprotocol-v4-proto-py', exact=True) }}
    test:
      imports:
        - v4_proto
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/dydxprotocol/v4-chain
  summary: 'The dYdX v4 software (the ”dYdX Chain”) is a sovereign blockchain software built using Cosmos SDK and CometBFT.'
  description: |
    The dYdX v4 software (the ”dYdX Chain”) is a sovereign blockchain software built using
    Cosmos SDK and CometBFT. It powers a robust decentralized perpetual futures exchange
    with a high-performance orderbook and matching engine for a feature-rich, self-custodial
    perpetual trading experience on any market.
  license: AGPL-3.0-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: dydxprotocol-v4-proto-py
