FROM mcr.microsoft.com/windows/servercore:ltsc2022
RUN powershell -Command `
    "Set-ExecutionPolicy Bypass -Scope Process -Force; `
    `[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
    `iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); `
    `choco install protobuf -y; `
    `choco install buf -y"
WORKDIR /workspace